// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBw3RzKwWYMO7BpTfh8MxE-6AdXDvlov0',
    appId: '1:1022206640461:web:9f932f0a68a7d104c73704',
    messagingSenderId: '1022206640461',
    projectId: 'notificationfire-68bc6',
    authDomain: 'notificationfire-68bc6.firebaseapp.com',
    storageBucket: 'notificationfire-68bc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiC9iWAsp1zMT6EoRt98G-wu8JX8rv9Fc',
    appId: '1:1022206640461:android:9b86aa11ef6e6d0dc73704',
    messagingSenderId: '1022206640461',
    projectId: 'notificationfire-68bc6',
    storageBucket: 'notificationfire-68bc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHSyIPTmQlSgdVJUbzPmGaorxeUKPqhgo',
    appId: '1:1022206640461:ios:1309f568e7aed650c73704',
    messagingSenderId: '1022206640461',
    projectId: 'notificationfire-68bc6',
    storageBucket: 'notificationfire-68bc6.appspot.com',
    iosBundleId: 'com.example.notificationswithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHSyIPTmQlSgdVJUbzPmGaorxeUKPqhgo',
    appId: '1:1022206640461:ios:1309f568e7aed650c73704',
    messagingSenderId: '1022206640461',
    projectId: 'notificationfire-68bc6',
    storageBucket: 'notificationfire-68bc6.appspot.com',
    iosBundleId: 'com.example.notificationswithfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBw3RzKwWYMO7BpTfh8MxE-6AdXDvlov0',
    appId: '1:1022206640461:web:49affb35d2cb58fdc73704',
    messagingSenderId: '1022206640461',
    projectId: 'notificationfire-68bc6',
    authDomain: 'notificationfire-68bc6.firebaseapp.com',
    storageBucket: 'notificationfire-68bc6.appspot.com',
  );
}
